var hierarchy =
[
    [ "fitpack_fitters::comm_expand_if", "interfacefitpack__fitters_1_1comm__expand__if.html", null ],
    [ "fitpack_fitters::comm_pack_if", "interfacefitpack__fitters_1_1comm__pack__if.html", null ],
    [ "fitpack_fitters::comm_size_if", "interfacefitpack__fitters_1_1comm__size__if.html", null ],
    [ "fitpack_convex_curves_c::f_associated", "interfacefitpack__convex__curves__c_1_1f__associated.html", null ],
    [ "fitpack_curves_c::f_associated", "interfacefitpack__curves__c_1_1f__associated.html", null ],
    [ "fitpack_fitters_c::f_associated", "interfacefitpack__fitters__c_1_1f__associated.html", null ],
    [ "fitpack_gridded_polar_c::f_associated", "interfacefitpack__gridded__polar__c_1_1f__associated.html", null ],
    [ "fitpack_gridded_sphere_c::f_associated", "interfacefitpack__gridded__sphere__c_1_1f__associated.html", null ],
    [ "fitpack_gridded_splines_c::f_associated", "interfacefitpack__gridded__splines__c_1_1f__associated.html", null ],
    [ "fitpack_gridded_surfaces_c::f_associated", "interfacefitpack__gridded__surfaces__c_1_1f__associated.html", null ],
    [ "fitpack_parametric_curves_c::f_associated", "interfacefitpack__parametric__curves__c_1_1f__associated.html", null ],
    [ "fitpack_parametric_surfaces_c::f_associated", "interfacefitpack__parametric__surfaces__c_1_1f__associated.html", null ],
    [ "fitpack_polar_domains_c::f_associated", "interfacefitpack__polar__domains__c_1_1f__associated.html", null ],
    [ "fitpack_sphere_domains_c::f_associated", "interfacefitpack__sphere__domains__c_1_1f__associated.html", null ],
    [ "fitpack_surfaces_c::f_associated", "interfacefitpack__surfaces__c_1_1f__associated.html", null ],
    [ "fitpack_fitters_c::f_char", "interfacefitpack__fitters__c_1_1f__char.html", null ],
    [ "fitpack_gridded_polar_c::f_char", "interfacefitpack__gridded__polar__c_1_1f__char.html", null ],
    [ "fitpack_gridded_sphere_c::f_char", "interfacefitpack__gridded__sphere__c_1_1f__char.html", null ],
    [ "fitpack_convex_curves_c::f_pointer", "interfacefitpack__convex__curves__c_1_1f__pointer.html", null ],
    [ "fitpack_curves_c::f_pointer", "interfacefitpack__curves__c_1_1f__pointer.html", null ],
    [ "fitpack_fitters_c::f_pointer", "interfacefitpack__fitters__c_1_1f__pointer.html", null ],
    [ "fitpack_gridded_polar_c::f_pointer", "interfacefitpack__gridded__polar__c_1_1f__pointer.html", null ],
    [ "fitpack_gridded_sphere_c::f_pointer", "interfacefitpack__gridded__sphere__c_1_1f__pointer.html", null ],
    [ "fitpack_gridded_splines_c::f_pointer", "interfacefitpack__gridded__splines__c_1_1f__pointer.html", null ],
    [ "fitpack_gridded_surfaces_c::f_pointer", "interfacefitpack__gridded__surfaces__c_1_1f__pointer.html", null ],
    [ "fitpack_parametric_curves_c::f_pointer", "interfacefitpack__parametric__curves__c_1_1f__pointer.html", null ],
    [ "fitpack_parametric_surfaces_c::f_pointer", "interfacefitpack__parametric__surfaces__c_1_1f__pointer.html", null ],
    [ "fitpack_polar_domains_c::f_pointer", "interfacefitpack__polar__domains__c_1_1f__pointer.html", null ],
    [ "fitpack_sphere_domains_c::f_pointer", "interfacefitpack__sphere__domains__c_1_1f__pointer.html", null ],
    [ "fitpack_surfaces_c::f_pointer", "interfacefitpack__surfaces__c_1_1f__pointer.html", null ],
    [ "fitpack_fitters_c::f_poly_pointer", "interfacefitpack__fitters__c_1_1f__poly__pointer.html", null ],
    [ "fitpack_convex_curves_c_types::f_type_name", "interfacefitpack__convex__curves__c__types_1_1f__type__name.html", null ],
    [ "fitpack_curves_c_types::f_type_name", "interfacefitpack__curves__c__types_1_1f__type__name.html", null ],
    [ "fitpack_fitters_c_types::f_type_name", "interfacefitpack__fitters__c__types_1_1f__type__name.html", null ],
    [ "fitpack_gridded_polar_c_types::f_type_name", "interfacefitpack__gridded__polar__c__types_1_1f__type__name.html", null ],
    [ "fitpack_gridded_sphere_c_types::f_type_name", "interfacefitpack__gridded__sphere__c__types_1_1f__type__name.html", null ],
    [ "fitpack_gridded_splines_c_types::f_type_name", "interfacefitpack__gridded__splines__c__types_1_1f__type__name.html", null ],
    [ "fitpack_gridded_surfaces_c_types::f_type_name", "interfacefitpack__gridded__surfaces__c__types_1_1f__type__name.html", null ],
    [ "fitpack_parametric_curves_c_types::f_type_name", "interfacefitpack__parametric__curves__c__types_1_1f__type__name.html", null ],
    [ "fitpack_parametric_surfaces_c_types::f_type_name", "interfacefitpack__parametric__surfaces__c__types_1_1f__type__name.html", null ],
    [ "fitpack_polar_domains_c_types::f_type_name", "interfacefitpack__polar__domains__c__types_1_1f__type__name.html", null ],
    [ "fitpack_sphere_domains_c_types::f_type_name", "interfacefitpack__sphere__domains__c__types_1_1f__type__name.html", null ],
    [ "fitpack_surfaces_c_types::f_type_name", "interfacefitpack__surfaces__c__types_1_1f__type__name.html", null ],
    [ "fitpack_parametric_curves_c_types::fitpack_closed_curve_c", "structfitpack__parametric__curves__c__types_1_1fitpack__closed__curve__c.html", null ],
    [ "fitpack_parametric_curves_c_types::fitpack_constrained_curve_c", "structfitpack__parametric__curves__c__types_1_1fitpack__constrained__curve__c.html", null ],
    [ "fitpack_convex_curves_c::fitpack_convex_curve_c", "interfacefitpack__convex__curves__c_1_1fitpack__convex__curve__c.html", null ],
    [ "fitpack_convex_curves_c_types::fitpack_convex_curve_c", "structfitpack__convex__curves__c__types_1_1fitpack__convex__curve__c.html", null ],
    [ "fitpack_curves_c_types::fitpack_curve_c", "structfitpack__curves__c__types_1_1fitpack__curve__c.html", null ],
    [ "fitpack_fitters::fitpack_fitter", "structfitpack__fitters_1_1fitpack__fitter.html", [
      [ "fitpack_curves::fitpack_curve", "structfitpack__curves_1_1fitpack__curve.html", [
        [ "fitpack_convex_curves::fitpack_convex_curve", "structfitpack__convex__curves_1_1fitpack__convex__curve.html", null ],
        [ "fitpack_curves::fitpack_periodic_curve", "structfitpack__curves_1_1fitpack__periodic__curve.html", null ]
      ] ],
      [ "fitpack_gridded_polar::fitpack_grid_polar", "structfitpack__gridded__polar_1_1fitpack__grid__polar.html", null ],
      [ "fitpack_gridded_sphere::fitpack_grid_sphere", "structfitpack__gridded__sphere_1_1fitpack__grid__sphere.html", null ],
      [ "fitpack_gridded_splines::fitpack_gridded_spline", "structfitpack__gridded__splines_1_1fitpack__gridded__spline.html", null ],
      [ "fitpack_gridded_surfaces::fitpack_grid_surface", "structfitpack__gridded__surfaces_1_1fitpack__grid__surface.html", null ],
      [ "fitpack_parametric_curves::fitpack_parametric_curve", "structfitpack__parametric__curves_1_1fitpack__parametric__curve.html", [
        [ "fitpack_parametric_curves::fitpack_closed_curve", "structfitpack__parametric__curves_1_1fitpack__closed__curve.html", null ],
        [ "fitpack_parametric_curves::fitpack_constrained_curve", "structfitpack__parametric__curves_1_1fitpack__constrained__curve.html", null ]
      ] ],
      [ "fitpack_parametric_surfaces::fitpack_parametric_surface", "structfitpack__parametric__surfaces_1_1fitpack__parametric__surface.html", null ],
      [ "fitpack_polar_domains::fitpack_polar", "structfitpack__polar__domains_1_1fitpack__polar.html", null ],
      [ "fitpack_sphere_domains::fitpack_sphere", "structfitpack__sphere__domains_1_1fitpack__sphere.html", null ],
      [ "fitpack_surfaces::fitpack_surface", "structfitpack__surfaces_1_1fitpack__surface.html", null ]
    ] ],
    [ "fitpack_fitters_c_types::fitpack_fitter_c", "structfitpack__fitters__c__types_1_1fitpack__fitter__c.html", null ],
    [ "fitpack_gridded_polar_c::fitpack_grid_polar_c", "interfacefitpack__gridded__polar__c_1_1fitpack__grid__polar__c.html", null ],
    [ "fitpack_gridded_polar_c_types::fitpack_grid_polar_c", "structfitpack__gridded__polar__c__types_1_1fitpack__grid__polar__c.html", null ],
    [ "fitpack_gridded_sphere_c::fitpack_grid_sphere_c", "interfacefitpack__gridded__sphere__c_1_1fitpack__grid__sphere__c.html", null ],
    [ "fitpack_gridded_sphere_c_types::fitpack_grid_sphere_c", "structfitpack__gridded__sphere__c__types_1_1fitpack__grid__sphere__c.html", null ],
    [ "fitpack_gridded_surfaces_c::fitpack_grid_surface_c", "interfacefitpack__gridded__surfaces__c_1_1fitpack__grid__surface__c.html", null ],
    [ "fitpack_gridded_surfaces_c_types::fitpack_grid_surface_c", "structfitpack__gridded__surfaces__c__types_1_1fitpack__grid__surface__c.html", null ],
    [ "fitpack_gridded_splines_c::fitpack_gridded_spline_c", "interfacefitpack__gridded__splines__c_1_1fitpack__gridded__spline__c.html", null ],
    [ "fitpack_gridded_splines_c_types::fitpack_gridded_spline_c", "structfitpack__gridded__splines__c__types_1_1fitpack__gridded__spline__c.html", null ],
    [ "fitpack_parametric_curves_c_types::fitpack_parametric_curve_c", "structfitpack__parametric__curves__c__types_1_1fitpack__parametric__curve__c.html", null ],
    [ "fitpack_parametric_surfaces_c::fitpack_parametric_surface_c", "interfacefitpack__parametric__surfaces__c_1_1fitpack__parametric__surface__c.html", null ],
    [ "fitpack_parametric_surfaces_c_types::fitpack_parametric_surface_c", "structfitpack__parametric__surfaces__c__types_1_1fitpack__parametric__surface__c.html", null ],
    [ "fitpack_curves_c_types::fitpack_periodic_curve_c", "structfitpack__curves__c__types_1_1fitpack__periodic__curve__c.html", null ],
    [ "fitpack_core::fitpack_polar_boundary", "interfacefitpack__core_1_1fitpack__polar__boundary.html", null ],
    [ "fitpack_polar_domains_c::fitpack_polar_boundary_capi", "interfacefitpack__polar__domains__c_1_1fitpack__polar__boundary__capi.html", null ],
    [ "fitpack_polar_domains_c::fitpack_polar_c", "interfacefitpack__polar__domains__c_1_1fitpack__polar__c.html", null ],
    [ "fitpack_polar_domains_c_types::fitpack_polar_c", "structfitpack__polar__domains__c__types_1_1fitpack__polar__c.html", null ],
    [ "fitpack_sphere_domains_c::fitpack_sphere_c", "interfacefitpack__sphere__domains__c_1_1fitpack__sphere__c.html", null ],
    [ "fitpack_sphere_domains_c_types::fitpack_sphere_c", "structfitpack__sphere__domains__c__types_1_1fitpack__sphere__c.html", null ],
    [ "fitpack_surfaces_c::fitpack_surface_c", "interfacefitpack__surfaces__c_1_1fitpack__surface__c.html", null ],
    [ "fitpack_surfaces_c_types::fitpack_surface_c", "structfitpack__surfaces__c__types_1_1fitpack__surface__c.html", null ],
    [ "fitpack_core::fitpack_swap", "interfacefitpack__core_1_1fitpack__swap.html", null ],
    [ "fitpack_core::fp_comm_expand", "interfacefitpack__core_1_1fp__comm__expand.html", null ],
    [ "fitpack_core::fp_comm_pack", "interfacefitpack__core_1_1fp__comm__pack.html", null ],
    [ "fitpack_core::fp_comm_size", "interfacefitpack__core_1_1fp__comm__size.html", null ],
    [ "fpFitter", "classfp_fitter.html", [
      [ "fpCurve", "classfp_curve.html", [
        [ "fpConvexCurve", "classfp_convex_curve.html", null ],
        [ "fpPeriodicCurve", "classfp_periodic_curve.html", null ]
      ] ],
      [ "fpGridPolar", "classfp_grid_polar.html", null ],
      [ "fpGridSphere", "classfp_grid_sphere.html", null ],
      [ "fpGridSpline", "classfp_grid_spline.html", null ],
      [ "fpGridSurface", "classfp_grid_surface.html", null ],
      [ "fpParametricCurve", "classfp_parametric_curve.html", [
        [ "fpClosedCurve", "classfp_closed_curve.html", null ],
        [ "fpConstrainedCurve", "classfp_constrained_curve.html", null ]
      ] ],
      [ "fpParametricSurface", "classfp_parametric_surface.html", null ],
      [ "fpPolar", "classfp_polar.html", null ],
      [ "fpSphere", "classfp_sphere.html", null ],
      [ "fpSurface", "classfp_surface.html", null ]
    ] ],
    [ "fpPoint< dims >", "structfp_point.html", null ],
    [ "fp_detail::fpPointLayout< dims >", "structfp__detail_1_1fp_point_layout.html", null ],
    [ "fitpack_fx_status::fx_status", "structfitpack__fx__status_1_1fx__status.html", null ],
    [ "fpFitter::NoAlloc", "structfp_fitter_1_1_no_alloc.html", null ],
    [ "fpFitter::ViewTag", "structfp_fitter_1_1_view_tag.html", null ]
];