var searchData=
[
  ['parameterization_0',['Parameterization',['../theory_curve_fitting.html#autotoc_md28',1,'Chord-Length Parameterization'],['../tutorial_parametric_curves.html#autotoc_md94',1,'Chord-Length Parameterization']]],
  ['parametric_20closed_20and_20constrained_20curves_1',['Parametric, Closed, and Constrained Curves',['../tutorial_parametric_curves.html',1,'']]],
  ['parametric_20curves_2',['Parametric Curves',['../theory_curve_fitting.html#autotoc_md27',1,'Parametric Curves'],['../tutorial_parametric_curves.html#autotoc_md93',1,'Parametric Curves']]],
  ['parametric_20surface_20tutorial_3',['Grid and Parametric Surface Tutorial',['../tutorial_grid_surface.html',1,'']]],
  ['parametric_20surfaces_4',['Parametric Surfaces',['../theory_surface_fitting.html#autotoc_md50',1,'']]],
  ['partial_20derivatives_5',['Partial Derivatives',['../tutorial_grid_surface.html#autotoc_md131',1,'']]],
  ['partial_20derivatives_6',['Partial derivatives',['../tutorial_surface.html#autotoc_md120',1,'']]],
  ['peaks_20function_20on_20a_20grid_7',['Example: Peaks Function on a Grid',['../tutorial_grid_surface.html#autotoc_md134',1,'']]],
  ['per_20interval_20convexity_20flags_8',['Per-Interval Convexity Flags',['../theory_curve_fitting.html#autotoc_md34',1,'']]],
  ['periodic_20curve_20fitting_9',['Periodic Curve Fitting',['../tutorial_periodic_curve.html',1,'']]],
  ['periodic_20splines_10',['Periodic Splines',['../theory_curve_fitting.html#autotoc_md26',1,'']]],
  ['periodic_5fdim_11',['periodic_dim',['../structfitpack__parametric__surfaces_1_1fitpack__parametric__surface.html#a2547c7ea9c3ad5199868621967d44b66',1,'fitpack_parametric_surfaces::fitpack_parametric_surface']]],
  ['periodicity_12',['Periodicity',['../theory_surface_fitting.html#autotoc_md51',1,'']]],
  ['periodicity_20in_20longitude_13',['Periodicity in longitude',['../theory_special_domains.html#autotoc_md64',1,'']]],
  ['periodicity_20verification_14',['Periodicity Verification',['../tutorial_periodic_curve.html#autotoc_md88',1,'']]],
  ['piecewise_20polynomials_20and_20knot_20vectors_15',['Piecewise Polynomials and Knot Vectors',['../theory_bsplines.html#autotoc_md7',1,'']]],
  ['placement_16',['Placement',['../theory_curve_fitting.html#autotoc_md24',1,'Adaptive Knot Placement'],['../theory_surface_fitting.html#autotoc_md43',1,'Adaptive Knot Placement']]],
  ['point_20evaluation_17',['Point evaluation',['../tutorial_surface.html#autotoc_md118',1,'']]],
  ['polar_20and_20spherical_20domains_18',['Polar and Spherical Domains',['../theory_special_domains.html',1,'Polar and Spherical Domains'],['../book_reference.html#autotoc_md6',1,'Polar and Spherical Domains']]],
  ['polar_20coordinates_19',['Polar Coordinates',['../theory_special_domains.html#autotoc_md53',1,'']]],
  ['polar_20coordinates_20',['Normalized polar coordinates',['../tutorial_polar.html#autotoc_md144',1,'']]],
  ['polar_20domain_21',['The polar domain',['../theory_special_domains.html#autotoc_md54',1,'']]],
  ['polar_20domain_20fitting_20tutorial_22',['Polar Domain Fitting Tutorial',['../tutorial_polar.html',1,'']]],
  ['polar_20grid_23',['Example: data on a polar grid',['../tutorial_polar.html#autotoc_md150',1,'']]],
  ['polar_20transform_24',['Normalized polar transform',['../theory_special_domains.html#autotoc_md55',1,'']]],
  ['pole_20boundary_20conditions_25',['Pole Boundary Conditions',['../tutorial_sphere.html#autotoc_md164',1,'']]],
  ['pole_20boundary_20conditions_20for_20gridded_20spheres_26',['Pole boundary conditions for gridded spheres',['../theory_special_domains.html#autotoc_md69',1,'']]],
  ['pole_20problem_27',['Pole Problem',['../theory_special_domains.html#autotoc_md66',1,'The Pole Problem'],['../tutorial_sphere.html#autotoc_md156',1,'The Pole Problem']]],
  ['pole_5fz0_28',['pole_z0',['../structfitpack__gridded__sphere_1_1fitpack__grid__sphere.html#a2e6ee63f9a155f5c31ead90f03ca222f',1,'fitpack_gridded_sphere::fitpack_grid_sphere']]],
  ['polynomials_20and_20knot_20vectors_29',['Piecewise Polynomials and Knot Vectors',['../theory_bsplines.html#autotoc_md7',1,'']]],
  ['practical_20considerations_30',['Practical Considerations',['../theory_special_domains.html#autotoc_md70',1,'']]],
  ['practical_20guidelines_31',['Practical Guidelines',['../theory_surface_fitting.html#autotoc_md49',1,'']]],
  ['prescribed_20tangents_32',['Example: Spiral with Prescribed Tangents',['../tutorial_parametric_curves.html#autotoc_md101',1,'']]],
  ['problem_33',['Problem',['../theory_curve_fitting.html#autotoc_md19',1,'The Approximation Problem'],['../theory_special_domains.html#autotoc_md66',1,'The Pole Problem'],['../tutorial_sphere.html#autotoc_md156',1,'The Pole Problem'],['../theory_curve_fitting.html#autotoc_md23',1,'The Smoothing Problem']]],
  ['problem_34',['problem',['../theory_special_domains.html#autotoc_md67',1,'Analogy with the origin problem'],['../theory_special_domains.html#autotoc_md58',1,'The problem']]],
  ['product_20splines_35',['Tensor Product Splines',['../theory_surface_fitting.html#autotoc_md37',1,'']]],
  ['product_20structure_36',['Kronecker Product Structure',['../theory_surface_fitting.html#autotoc_md45',1,'']]],
  ['products_20for_20bivariate_20splines_37',['Tensor Products for Bivariate Splines',['../theory_bsplines.html#autotoc_md17',1,'']]],
  ['programming_20formulation_38',['Quadratic Programming Formulation',['../theory_curve_fitting.html#autotoc_md35',1,'']]],
  ['properties_39',['Key properties',['../theory_bsplines.html#autotoc_md11',1,'']]]
];
