var searchData=
[
  ['a_20curve_0',['Fit a curve',['../index.html#autotoc_md3',1,'']]],
  ['a_20fit_1',['a Fit',['../tutorial_grid_surface.html#autotoc_md141',1,'Creating a Fit'],['../tutorial_grid_surface.html#autotoc_md149',1,'Creating a Fit']]],
  ['a_20grid_2',['Example: Peaks Function on a Grid',['../tutorial_grid_surface.html#autotoc_md146',1,'']]],
  ['a_20lat_20lon_20grid_3',['Example: Function on a Lat-Lon Grid',['../tutorial_sphere.html#autotoc_md177',1,'']]],
  ['a_20linear_20combination_4',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md24',1,'']]],
  ['a_20polar_20grid_5',['Example: data on a polar grid',['../tutorial_polar.html#autotoc_md162',1,'']]],
  ['a_20surface_6',['Fit a surface',['../index.html#autotoc_md4',1,'']]],
  ['a_20torus_7',['Example: Fitting a Torus',['../tutorial_grid_surface.html#autotoc_md151',1,'']]],
  ['a_20unit_20disc_8',['Example: smooth function on a unit disc',['../tutorial_polar.html#autotoc_md159',1,'']]],
  ['across_20the_20boundary_9',['Integration Across the Boundary',['../tutorial_periodic_curve.html#autotoc_md101',1,'']]],
  ['adaptive_20knot_20placement_10',['Adaptive Knot Placement',['../theory_curve_fitting.html#autotoc_md36',1,'Adaptive Knot Placement'],['../theory_surface_fitting.html#autotoc_md55',1,'Adaptive Knot Placement']]],
  ['advanced_20features_11',['Advanced Features',['../tutorial_curve.html#autotoc_md87',1,'']]],
  ['advantage_12',['Computational Advantage',['../theory_surface_fitting.html#autotoc_md58',1,'']]],
  ['algorithm_13',['Algorithm',['../theory_bsplines.html#autotoc_md25',1,'Evaluation: the de Boor Algorithm'],['../theory_bsplines.html#autotoc_md28',1,'Knot Insertion (Oslo Algorithm)']]],
  ['algorithms_14',['Core Algorithms',['../book_reference.html#autotoc_md13',1,'']]],
  ['allocate_5fknot_5fstorage_15',['allocate_knot_storage',['../namespacefitpack__parametric__surfaces.html#acaa4898491130825fd5a1ed122aefe58',1,'fitpack_parametric_surfaces']]],
  ['analogy_20with_20the_20origin_20problem_16',['Analogy with the origin problem',['../theory_special_domains.html#autotoc_md79',1,'']]],
  ['and_20banded_20structure_17',['Normal Equations and Banded Structure',['../theory_curve_fitting.html#autotoc_md33',1,'']]],
  ['and_20constrained_20curves_18',['Parametric, Closed, and Constrained Curves',['../tutorial_parametric_curves.html',1,'']]],
  ['and_20derivative_20splines_19',['Cross-Sections and Derivative Splines',['../tutorial_grid_surface.html#autotoc_md145',1,'']]],
  ['and_20fitting_20',['and Fitting',['../tutorial_sphere.html#autotoc_md171',1,'Construction and Fitting'],['../tutorial_sphere.html#autotoc_md175',1,'Construction and Fitting']]],
  ['and_20inspect_21',['Step 3 — Evaluate and Inspect',['../tutorial_convex_curve.html#autotoc_md121',1,'']]],
  ['and_20interpolation_22',['Smoothing and Interpolation',['../tutorial_periodic_curve.html#autotoc_md102',1,'']]],
  ['and_20knot_20vectors_23',['Piecewise Polynomials and Knot Vectors',['../theory_bsplines.html#autotoc_md19',1,'']]],
  ['and_20parametric_20surface_20tutorial_24',['Grid and Parametric Surface Tutorial',['../tutorial_grid_surface.html',1,'']]],
  ['and_20set_20convexity_20flags_25',['Step 1 — Load Data and Set Convexity Flags',['../tutorial_convex_curve.html#autotoc_md119',1,'']]],
  ['and_20spherical_20domains_26',['and Spherical Domains',['../theory_special_domains.html',1,'Polar and Spherical Domains'],['../book_reference.html#autotoc_md18',1,'Polar and Spherical Domains']]],
  ['api_27',['API',['../tutorial_parametric_curves.html#autotoc_md107',1,'']]],
  ['api_20summary_28',['API Summary',['../tutorial_curve.html#autotoc_md94',1,'API Summary'],['../tutorial_convex_curve.html#autotoc_md125',1,'API Summary']]],
  ['approximation_20problem_29',['The Approximation Problem',['../theory_curve_fitting.html#autotoc_md31',1,'']]],
  ['as_20a_20linear_20combination_30',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md24',1,'']]],
  ['at_20the_20origin_31',['Continuity at the Origin',['../theory_special_domains.html#autotoc_md69',1,'']]],
  ['at_20the_20origin_32',['Continuity at the origin',['../tutorial_polar.html#autotoc_md157',1,'']]]
];
