var searchData=
[
  ['t_0',['t',['../structfitpack__curves_1_1fitpack__curve.html#ac0d07388dd8ecf66645fa07e524f9a60',1,'fitpack_curves::fitpack_curve::t'],['../structfitpack__grid__surfaces_1_1fitpack__grid__surface.html#ab2669908b8eca92eb09f0d8e2cabc43d',1,'fitpack_grid_surfaces::fitpack_grid_surface::t'],['../structfitpack__gridded__polar_1_1fitpack__grid__polar.html#a202ff1b24110c1d549617308443ccc1f',1,'fitpack_gridded_polar::fitpack_grid_polar::t'],['../structfitpack__gridded__sphere_1_1fitpack__grid__sphere.html#a93239e583a193e80a0fa4ea5ec61864c',1,'fitpack_gridded_sphere::fitpack_grid_sphere::t'],['../structfitpack__parametric__curves_1_1fitpack__parametric__curve.html#a671acc4f04dbd187cd60fd86fc89e350',1,'fitpack_parametric_curves::fitpack_parametric_curve::t'],['../structfitpack__parametric__surfaces_1_1fitpack__parametric__surface.html#a2f3895df363acdab545d1bbaeeb0b4d2',1,'fitpack_parametric_surfaces::fitpack_parametric_surface::t'],['../structfitpack__polar__domains_1_1fitpack__polar.html#a4b24fca3eff8d98451e0c461f13d5584',1,'fitpack_polar_domains::fitpack_polar::t'],['../structfitpack__sphere__domains_1_1fitpack__sphere.html#a7788accceb58102e964479e788328b77',1,'fitpack_sphere_domains::fitpack_sphere::t'],['../structfitpack__surfaces_1_1fitpack__surface.html#ac22802b09c85652f411d1bf090b8c7da',1,'fitpack_surfaces::fitpack_surface::t']]],
  ['tangents_1',['Example: Spiral with Prescribed Tangents',['../tutorial_parametric_curves.html#autotoc_md113',1,'']]],
  ['ten_2',['ten',['../namespacefitpack__core.html#a5de665dd2a4942cc8f8e3a7f9d6ca47c',1,'fitpack_core']]],
  ['tensor_20product_20splines_3',['Tensor Product Splines',['../theory_surface_fitting.html#autotoc_md49',1,'']]],
  ['tensor_20products_20for_20bivariate_20splines_4',['Tensor Products for Bivariate Splines',['../theory_bsplines.html#autotoc_md29',1,'']]],
  ['test_20function_5',['Example: Spherical Harmonic Test Function',['../tutorial_sphere.html#autotoc_md173',1,'']]],
  ['the_20approximation_20problem_6',['The Approximation Problem',['../theory_curve_fitting.html#autotoc_md31',1,'']]],
  ['the_20boundary_7',['Integration Across the Boundary',['../tutorial_periodic_curve.html#autotoc_md101',1,'']]],
  ['the_20de_20boor_20algorithm_8',['Evaluation: the de Boor Algorithm',['../theory_bsplines.html#autotoc_md25',1,'']]],
  ['the_20disc_20edge_9',['Boundary Conditions on the Disc Edge',['../theory_special_domains.html#autotoc_md73',1,'']]],
  ['the_20observation_20matrix_10',['The Observation Matrix',['../theory_surface_fitting.html#autotoc_md51',1,'']]],
  ['the_20origin_11',['Continuity at the Origin',['../theory_special_domains.html#autotoc_md69',1,'']]],
  ['the_20origin_12',['Continuity at the origin',['../tutorial_polar.html#autotoc_md157',1,'']]],
  ['the_20origin_20problem_13',['Analogy with the origin problem',['../theory_special_domains.html#autotoc_md79',1,'']]],
  ['the_20polar_20domain_14',['The polar domain',['../theory_special_domains.html#autotoc_md66',1,'']]],
  ['the_20pole_20problem_15',['The Pole Problem',['../theory_special_domains.html#autotoc_md78',1,'The Pole Problem'],['../tutorial_sphere.html#autotoc_md168',1,'The Pole Problem']]],
  ['the_20problem_16',['The problem',['../theory_special_domains.html#autotoc_md70',1,'']]],
  ['the_20smoothing_20factor_17',['the Smoothing Factor',['../theory_curve_fitting.html#autotoc_md37',1,'Choosing the Smoothing Factor'],['../theory_surface_fitting.html#autotoc_md60',1,'Choosing the Smoothing Factor']]],
  ['the_20smoothing_20norm_18',['The Smoothing Norm',['../theory_surface_fitting.html#autotoc_md59',1,'']]],
  ['the_20smoothing_20problem_19',['The Smoothing Problem',['../theory_curve_fitting.html#autotoc_md35',1,'']]],
  ['the_20spherical_20domain_20',['The spherical domain',['../theory_special_domains.html#autotoc_md75',1,'']]],
  ['theory_21',['Theory',['../theory_curve_fitting.html',1,'Curve Fitting Theory'],['../index.html#autotoc_md6',1,'Spline Theory'],['../theory_surface_fitting.html',1,'Surface Fitting Theory']]],
  ['theory_5fbsplines_2emd_22',['theory_bsplines.md',['../theory__bsplines_8md.html',1,'']]],
  ['theory_5fcurve_5ffitting_2emd_23',['theory_curve_fitting.md',['../theory__curve__fitting_8md.html',1,'']]],
  ['theory_5fspecial_5fdomains_2emd_24',['theory_special_domains.md',['../theory__special__domains_8md.html',1,'']]],
  ['theory_5fsurface_5ffitting_2emd_25',['theory_surface_fitting.md',['../theory__surface__fitting_8md.html',1,'']]],
  ['theta_26',['theta',['../structfitpack__sphere__domains_1_1fitpack__sphere.html#aa8dba44b26f9b4c94e4e4d1118925b06',1,'fitpack_sphere_domains::fitpack_sphere']]],
  ['third_27',['third',['../namespacefitpack__core.html#a2400f32cd48e2a9819ac8679d58ac20e',1,'fitpack_core']]],
  ['three_28',['three',['../namespacefitpack__core.html#a943cd42934fd393b333db11f752fc638',1,'fitpack_core']]],
  ['tobeswapped_29',['tobeswapped',['../fitpack__core_8_f90.html#a6e2d25f0c47b08f7fced619525b1a825',1,'fitpack_core.F90']]],
  ['torus_30',['Example: Fitting a Torus',['../tutorial_grid_surface.html#autotoc_md151',1,'']]],
  ['transform_31',['Normalized polar transform',['../theory_special_domains.html#autotoc_md67',1,'']]],
  ['tt_32',['tt',['../tutorial_polar.html#autotoc_md160',1,'Gridded Data: &lt;tt&gt;fitpack_grid_polar&lt;/tt&gt;'],['../tutorial_sphere.html#autotoc_md174',1,'Gridded Sphere Data — &lt;tt&gt;fitpack_grid_sphere&lt;/tt&gt;'],['../tutorial_polar.html#autotoc_md158',1,'Scattered Data: &lt;tt&gt;fitpack_polar&lt;/tt&gt;'],['../tutorial_sphere.html#autotoc_md170',1,'Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;']]],
  ['tt_20fitpack_5fgrid_5fpolar_20tt_33',['Gridded Data: &lt;tt&gt;fitpack_grid_polar&lt;/tt&gt;',['../tutorial_polar.html#autotoc_md160',1,'']]],
  ['tt_20fitpack_5fgrid_5fsphere_20tt_34',['Gridded Sphere Data — &lt;tt&gt;fitpack_grid_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md174',1,'']]],
  ['tt_20fitpack_5fpolar_20tt_35',['Scattered Data: &lt;tt&gt;fitpack_polar&lt;/tt&gt;',['../tutorial_polar.html#autotoc_md158',1,'']]],
  ['tt_20fitpack_5fsphere_20tt_36',['Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md170',1,'']]],
  ['tutorial_37',['Tutorial',['../tutorial_grid_surface.html',1,'Grid and Parametric Surface Tutorial'],['../tutorial_polar.html',1,'Polar Domain Fitting Tutorial'],['../tutorial_surface.html',1,'Scattered Surface Fitting Tutorial'],['../tutorial_sphere.html',1,'Spherical Spline Fitting Tutorial']]],
  ['tutorial_5fconvex_5fcurve_2emd_38',['tutorial_convex_curve.md',['../tutorial__convex__curve_8md.html',1,'']]],
  ['tutorial_5fcurve_2emd_39',['tutorial_curve.md',['../tutorial__curve_8md.html',1,'']]],
  ['tutorial_5fgrid_5fsurface_2emd_40',['tutorial_grid_surface.md',['../tutorial__grid__surface_8md.html',1,'']]],
  ['tutorial_5fparametric_5fcurves_2emd_41',['tutorial_parametric_curves.md',['../tutorial__parametric__curves_8md.html',1,'']]],
  ['tutorial_5fperiodic_5fcurve_2emd_42',['tutorial_periodic_curve.md',['../tutorial__periodic__curve_8md.html',1,'']]],
  ['tutorial_5fpolar_2emd_43',['tutorial_polar.md',['../tutorial__polar_8md.html',1,'']]],
  ['tutorial_5fsphere_2emd_44',['tutorial_sphere.md',['../tutorial__sphere_8md.html',1,'']]],
  ['tutorial_5fsurface_2emd_45',['tutorial_surface.md',['../tutorial__surface_8md.html',1,'']]],
  ['tutorials_46',['Tutorials',['../index.html#autotoc_md7',1,'']]],
  ['two_47',['two',['../namespacefitpack__core.html#afee03366ac96e05920c831ebe8d1a80b',1,'fitpack_core']]],
  ['type_20hierarchy_48',['Type Hierarchy',['../index.html#autotoc_md1',1,'']]]
];
