var searchData=
[
  ['a_20fit_0',['a Fit',['../tutorial_grid_surface.html#autotoc_md129',1,'Creating a Fit'],['../tutorial_grid_surface.html#autotoc_md137',1,'Creating a Fit']]],
  ['a_20grid_1',['Example: Peaks Function on a Grid',['../tutorial_grid_surface.html#autotoc_md134',1,'']]],
  ['a_20lat_20lon_20grid_2',['Example: Function on a Lat-Lon Grid',['../tutorial_sphere.html#autotoc_md165',1,'']]],
  ['a_20linear_20combination_3',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md12',1,'']]],
  ['a_20polar_20grid_4',['Example: data on a polar grid',['../tutorial_polar.html#autotoc_md150',1,'']]],
  ['a_20torus_5',['Example: Fitting a Torus',['../tutorial_grid_surface.html#autotoc_md139',1,'']]],
  ['a_20unit_20disc_6',['Example: smooth function on a unit disc',['../tutorial_polar.html#autotoc_md147',1,'']]],
  ['across_20the_20boundary_7',['Integration Across the Boundary',['../tutorial_periodic_curve.html#autotoc_md89',1,'']]],
  ['adaptive_20knot_20placement_8',['Adaptive Knot Placement',['../theory_curve_fitting.html#autotoc_md24',1,'Adaptive Knot Placement'],['../theory_surface_fitting.html#autotoc_md43',1,'Adaptive Knot Placement']]],
  ['advanced_20features_9',['Advanced Features',['../tutorial_curve.html#autotoc_md75',1,'']]],
  ['advantage_10',['Computational Advantage',['../theory_surface_fitting.html#autotoc_md46',1,'']]],
  ['algorithm_11',['Algorithm',['../theory_bsplines.html#autotoc_md13',1,'Evaluation: the de Boor Algorithm'],['../theory_bsplines.html#autotoc_md16',1,'Knot Insertion (Oslo Algorithm)']]],
  ['algorithms_12',['Core Algorithms',['../book_reference.html#autotoc_md1',1,'']]],
  ['analogy_20with_20the_20origin_20problem_13',['Analogy with the origin problem',['../theory_special_domains.html#autotoc_md67',1,'']]],
  ['and_20banded_20structure_14',['Normal Equations and Banded Structure',['../theory_curve_fitting.html#autotoc_md21',1,'']]],
  ['and_20constrained_20curves_15',['Parametric, Closed, and Constrained Curves',['../tutorial_parametric_curves.html',1,'']]],
  ['and_20derivative_20splines_16',['Cross-Sections and Derivative Splines',['../tutorial_grid_surface.html#autotoc_md133',1,'']]],
  ['and_20fitting_17',['and Fitting',['../tutorial_sphere.html#autotoc_md159',1,'Construction and Fitting'],['../tutorial_sphere.html#autotoc_md163',1,'Construction and Fitting']]],
  ['and_20inspect_18',['Step 3 — Evaluate and Inspect',['../tutorial_convex_curve.html#autotoc_md109',1,'']]],
  ['and_20interpolation_19',['Smoothing and Interpolation',['../tutorial_periodic_curve.html#autotoc_md90',1,'']]],
  ['and_20knot_20vectors_20',['Piecewise Polynomials and Knot Vectors',['../theory_bsplines.html#autotoc_md7',1,'']]],
  ['and_20parametric_20surface_20tutorial_21',['Grid and Parametric Surface Tutorial',['../tutorial_grid_surface.html',1,'']]],
  ['and_20set_20convexity_20flags_22',['Step 1 — Load Data and Set Convexity Flags',['../tutorial_convex_curve.html#autotoc_md107',1,'']]],
  ['and_20spherical_20domains_23',['and Spherical Domains',['../theory_special_domains.html',1,'Polar and Spherical Domains'],['../book_reference.html#autotoc_md6',1,'Polar and Spherical Domains']]],
  ['api_24',['API',['../tutorial_parametric_curves.html#autotoc_md95',1,'']]],
  ['api_20summary_25',['API Summary',['../tutorial_curve.html#autotoc_md82',1,'API Summary'],['../tutorial_convex_curve.html#autotoc_md113',1,'API Summary']]],
  ['approximation_20problem_26',['The Approximation Problem',['../theory_curve_fitting.html#autotoc_md19',1,'']]],
  ['as_20a_20linear_20combination_27',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md12',1,'']]],
  ['at_20the_20origin_28',['Continuity at the Origin',['../theory_special_domains.html#autotoc_md57',1,'']]],
  ['at_20the_20origin_29',['Continuity at the origin',['../tutorial_polar.html#autotoc_md145',1,'']]]
];
