var searchData=
[
  ['c_0',['c',['../structfitpack__fitters_1_1fitpack__fitter.html#a17057c7a2aa35ac6c0e87329a2e6ec66',1,'fitpack_fitters::fitpack_fitter']]],
  ['choosing_20s_1',['Choosing S',['../tutorial_curve.html#autotoc_md72',1,'']]],
  ['choosing_20the_20smoothing_20factor_2',['Choosing the Smoothing Factor',['../theory_curve_fitting.html#autotoc_md25',1,'Choosing the Smoothing Factor'],['../theory_surface_fitting.html#autotoc_md48',1,'Choosing the Smoothing Factor']]],
  ['chord_20length_20parameterization_3',['Chord Length Parameterization',['../theory_curve_fitting.html#autotoc_md28',1,'Chord-Length Parameterization'],['../tutorial_parametric_curves.html#autotoc_md94',1,'Chord-Length Parameterization']]],
  ['clean_5fconstraints_4',['clean_constraints',['../structfitpack__parametric__curves_1_1fitpack__constrained__curve.html#af4d60a4dc39a2954093fd70acc3efac8',1,'fitpack_parametric_curves::fitpack_constrained_curve']]],
  ['closed_20and_20constrained_20curves_5',['Parametric, Closed, and Constrained Curves',['../tutorial_parametric_curves.html',1,'']]],
  ['closed_20curves_6',['Closed Curves',['../theory_curve_fitting.html#autotoc_md30',1,'Closed Curves'],['../tutorial_parametric_curves.html#autotoc_md97',1,'Closed Curves']]],
  ['coefficient_20conditions_7',['B-Spline Coefficient Conditions',['../theory_curve_fitting.html#autotoc_md33',1,'']]],
  ['combination_8',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md12',1,'']]],
  ['comm_5fexpand_9',['comm_expand',['../structfitpack__convex__curves_1_1fitpack__convex__curve.html#a6d227de45d4a7299160718ed4c01e4bf',1,'fitpack_convex_curves::fitpack_convex_curve::comm_expand()'],['../structfitpack__curves_1_1fitpack__curve.html#ab4e3f6fc0b0d6f12faa8d8aed0a5a3c2',1,'fitpack_curves::fitpack_curve::comm_expand()']]],
  ['comm_5fpack_10',['comm_pack',['../structfitpack__convex__curves_1_1fitpack__convex__curve.html#a3ff3ad5e397c0b4ee81e51766cc0853f',1,'fitpack_convex_curves::fitpack_convex_curve::comm_pack()'],['../structfitpack__curves_1_1fitpack__curve.html#a8c84ac425d10251ec6e7602ebf74e235',1,'fitpack_curves::fitpack_curve::comm_pack()']]],
  ['comm_5fsize_11',['comm_size',['../structfitpack__convex__curves_1_1fitpack__convex__curve.html#a10b067bc8d577fb567bab91013e0147a',1,'fitpack_convex_curves::fitpack_convex_curve::comm_size()'],['../structfitpack__curves_1_1fitpack__curve.html#a9bffb5bd168bc305326812a86463eb56',1,'fitpack_curves::fitpack_curve::comm_size()'],['../structfitpack__fitters_1_1fitpack__fitter.html#af3f1bd18f36011f74337f85bf5a160a4',1,'fitpack_fitters::fitpack_fitter::comm_size()'],['../structfitpack__grid__surfaces_1_1fitpack__grid__surface.html#ab190b6d0ce917eac8bfbf4c0a577eea7',1,'fitpack_grid_surfaces::fitpack_grid_surface::comm_size()'],['../structfitpack__gridded__polar_1_1fitpack__grid__polar.html#a1ad1400e63ec5154bc7ae25e7766bd91',1,'fitpack_gridded_polar::fitpack_grid_polar::comm_size()'],['../structfitpack__gridded__sphere_1_1fitpack__grid__sphere.html#a923cfd29002690de3af45a58316d0389',1,'fitpack_gridded_sphere::fitpack_grid_sphere::comm_size()'],['../structfitpack__parametric__curves_1_1fitpack__parametric__curve.html#affa5c2c69c91582ae0b8cb7670c8cbe1',1,'fitpack_parametric_curves::fitpack_parametric_curve::comm_size()'],['../structfitpack__parametric__curves_1_1fitpack__constrained__curve.html#adab010fbdd6e623ac25a7ba3437cb257',1,'fitpack_parametric_curves::fitpack_constrained_curve::comm_size()'],['../structfitpack__parametric__surfaces_1_1fitpack__parametric__surface.html#a0f2610f64a3964d4a6a4afc7a586cb14',1,'fitpack_parametric_surfaces::fitpack_parametric_surface::comm_size()'],['../structfitpack__polar__domains_1_1fitpack__polar.html#ab8da154a4145144c0a846bcdf7e44313',1,'fitpack_polar_domains::fitpack_polar::comm_size()'],['../structfitpack__sphere__domains_1_1fitpack__sphere.html#ac30ed3b1aab1d4fe10f17a4474b8ede7',1,'fitpack_sphere_domains::fitpack_sphere::comm_size()'],['../structfitpack__surfaces_1_1fitpack__surface.html#a63eb9299dbd7fc3d8f1c65dc5b470ed5',1,'fitpack_surfaces::fitpack_surface::comm_size()']]],
  ['comm_5fsize_5fif_12',['comm_size_if',['../interfacefitpack__fitters_1_1comm__size__if.html',1,'fitpack_fitters']]],
  ['comparing_20constrained_20vs_20unconstrained_13',['Comparing Constrained vs Unconstrained',['../tutorial_convex_curve.html#autotoc_md110',1,'']]],
  ['complete_20example_14',['Complete Example',['../tutorial_curve.html#autotoc_md83',1,'Complete Example'],['../tutorial_periodic_curve.html#autotoc_md91',1,'Complete Example'],['../tutorial_parametric_curves.html#autotoc_md102',1,'Complete Example'],['../tutorial_convex_curve.html#autotoc_md114',1,'Complete Example'],['../tutorial_surface.html#autotoc_md127',1,'Complete Example'],['../tutorial_grid_surface.html#autotoc_md141',1,'Complete Example'],['../tutorial_polar.html#autotoc_md152',1,'Complete Example'],['../tutorial_sphere.html#autotoc_md166',1,'Complete Example']]],
  ['component_20surfaces_15',['Multi-Component Surfaces',['../tutorial_grid_surface.html#autotoc_md136',1,'']]],
  ['computational_20advantage_16',['Computational Advantage',['../theory_surface_fitting.html#autotoc_md46',1,'']]],
  ['conditions_17',['Conditions',['../theory_curve_fitting.html#autotoc_md33',1,'B-Spline Coefficient Conditions'],['../tutorial_sphere.html#autotoc_md164',1,'Pole Boundary Conditions']]],
  ['conditions_18',['conditions',['../theory_special_domains.html#autotoc_md68',1,'Continuity conditions'],['../tutorial_polar.html#autotoc_md149',1,'Origin boundary conditions']]],
  ['conditions_20for_20gridded_20spheres_19',['Pole boundary conditions for gridded spheres',['../theory_special_domains.html#autotoc_md69',1,'']]],
  ['conditions_20on_20the_20disc_20edge_20',['Boundary Conditions on the Disc Edge',['../theory_special_domains.html#autotoc_md61',1,'']]],
  ['connection_21',['Spherical Harmonics Connection',['../tutorial_sphere.html#autotoc_md157',1,'']]],
  ['considerations_22',['Practical Considerations',['../theory_special_domains.html#autotoc_md70',1,'']]],
  ['constrained_20curve_20fitting_23',['Convexity-Constrained Curve Fitting',['../tutorial_convex_curve.html',1,'']]],
  ['constrained_20curves_24',['Constrained Curves',['../tutorial_parametric_curves.html#autotoc_md99',1,'Constrained Curves'],['../tutorial_parametric_curves.html',1,'Parametric, Closed, and Constrained Curves']]],
  ['constrained_20fitting_25',['Convexity-Constrained Fitting',['../theory_curve_fitting.html#autotoc_md32',1,'']]],
  ['constrained_20vs_20unconstrained_26',['Comparing Constrained vs Unconstrained',['../tutorial_convex_curve.html#autotoc_md110',1,'']]],
  ['constraints_27',['Constraints',['../theory_curve_fitting.html#autotoc_md31',1,'Endpoint Constraints'],['../tutorial_convex_curve.html#autotoc_md111',1,'Mixed Constraints'],['../tutorial_parametric_curves.html#autotoc_md100',1,'Setting Constraints'],['../tutorial_convex_curve.html#autotoc_md108',1,'Step 2 — Fit with Constraints']]],
  ['construction_20and_20fitting_28',['Construction and Fitting',['../tutorial_sphere.html#autotoc_md159',1,'Construction and Fitting'],['../tutorial_sphere.html#autotoc_md163',1,'Construction and Fitting']]],
  ['constructor_20shortcut_29',['Constructor Shortcut',['../tutorial_convex_curve.html#autotoc_md112',1,'']]],
  ['continuity_20at_20the_20origin_30',['Continuity at the Origin',['../theory_special_domains.html#autotoc_md57',1,'']]],
  ['continuity_20at_20the_20origin_31',['Continuity at the origin',['../tutorial_polar.html#autotoc_md145',1,'']]],
  ['continuity_20conditions_32',['Continuity conditions',['../theory_special_domains.html#autotoc_md68',1,'']]],
  ['continuity_20orders_33',['Continuity orders',['../theory_special_domains.html#autotoc_md59',1,'']]],
  ['convexity_20constrained_20curve_20fitting_34',['Convexity-Constrained Curve Fitting',['../tutorial_convex_curve.html',1,'']]],
  ['convexity_20constrained_20fitting_35',['Convexity-Constrained Fitting',['../theory_curve_fitting.html#autotoc_md32',1,'']]],
  ['convexity_20flags_36',['Convexity Flags',['../theory_curve_fitting.html#autotoc_md34',1,'Per-Interval Convexity Flags'],['../tutorial_convex_curve.html#autotoc_md107',1,'Step 1 — Load Data and Set Convexity Flags']]],
  ['coordinates_37',['Coordinates',['../theory_special_domains.html#autotoc_md53',1,'Polar Coordinates'],['../theory_special_domains.html#autotoc_md62',1,'Spherical Coordinates']]],
  ['coordinates_38',['Normalized polar coordinates',['../tutorial_polar.html#autotoc_md144',1,'']]],
  ['core_20algorithms_39',['Core Algorithms',['../book_reference.html#autotoc_md1',1,'']]],
  ['core_5fcomm_5fexpand_40',['core_comm_expand',['../structfitpack__fitters_1_1fitpack__fitter.html#a84b552fc80bf0d9e48dab0528518510a',1,'fitpack_fitters::fitpack_fitter']]],
  ['core_5fcomm_5fpack_41',['core_comm_pack',['../structfitpack__fitters_1_1fitpack__fitter.html#a71f8f7fd77934f74258803c4518a4c56',1,'fitpack_fitters::fitpack_fitter']]],
  ['core_5fcomm_5fsize_42',['core_comm_size',['../structfitpack__fitters_1_1fitpack__fitter.html#ac96427338601093ec28b0462966cc138',1,'fitpack_fitters::fitpack_fitter']]],
  ['cp_43',['cp',['../structfitpack__parametric__curves_1_1fitpack__constrained__curve.html#a63429a5709be4b1f08598ca9849ed215',1,'fitpack_parametric_curves::fitpack_constrained_curve']]],
  ['creating_20a_20fit_44',['Creating a Fit',['../tutorial_grid_surface.html#autotoc_md129',1,'Creating a Fit'],['../tutorial_grid_surface.html#autotoc_md137',1,'Creating a Fit']]],
  ['cross_20sections_45',['Cross-sections',['../tutorial_surface.html#autotoc_md122',1,'']]],
  ['cross_20sections_20and_20derivative_20splines_46',['Cross-Sections and Derivative Splines',['../tutorial_grid_surface.html#autotoc_md133',1,'']]],
  ['cross_5fsection_47',['cross_section',['../structfitpack__grid__surfaces_1_1fitpack__grid__surface.html#ae948ba7749eb6fa1659a2a81117a4223',1,'fitpack_grid_surfaces::fitpack_grid_surface::cross_section()'],['../structfitpack__surfaces_1_1fitpack__surface.html#aff3a7e57d6f5836a262d29e442e7c0b5',1,'fitpack_surfaces::fitpack_surface::cross_section()']]],
  ['curve_20evaluation_48',['Curve Evaluation',['../book_reference.html#autotoc_md3',1,'']]],
  ['curve_20fitting_49',['Curve Fitting',['../tutorial_convex_curve.html',1,'Convexity-Constrained Curve Fitting'],['../tutorial_periodic_curve.html',1,'Periodic Curve Fitting']]],
  ['curve_20fitting_201d_50',['Curve Fitting (1D)',['../book_reference.html#autotoc_md2',1,'']]],
  ['curve_20fitting_20theory_51',['Curve Fitting Theory',['../theory_curve_fitting.html',1,'']]],
  ['curve_20fitting_20with_20fitpack_5fcurve_52',['Univariate Curve Fitting with fitpack_curve',['../tutorial_curve.html',1,'']]],
  ['curves_53',['Curves',['../theory_curve_fitting.html#autotoc_md30',1,'Closed Curves'],['../tutorial_parametric_curves.html#autotoc_md97',1,'Closed Curves'],['../tutorial_parametric_curves.html#autotoc_md99',1,'Constrained Curves'],['../theory_curve_fitting.html#autotoc_md27',1,'Parametric Curves'],['../tutorial_parametric_curves.html#autotoc_md93',1,'Parametric Curves'],['../tutorial_parametric_curves.html',1,'Parametric, Closed, and Constrained Curves']]]
];
