var searchData=
[
  ['tangents_0',['Example: Spiral with Prescribed Tangents',['../tutorial_parametric_curves.html#autotoc_md101',1,'']]],
  ['tensor_20product_20splines_1',['Tensor Product Splines',['../theory_surface_fitting.html#autotoc_md37',1,'']]],
  ['tensor_20products_20for_20bivariate_20splines_2',['Tensor Products for Bivariate Splines',['../theory_bsplines.html#autotoc_md17',1,'']]],
  ['test_20function_3',['Example: Spherical Harmonic Test Function',['../tutorial_sphere.html#autotoc_md161',1,'']]],
  ['the_20approximation_20problem_4',['The Approximation Problem',['../theory_curve_fitting.html#autotoc_md19',1,'']]],
  ['the_20boundary_5',['Integration Across the Boundary',['../tutorial_periodic_curve.html#autotoc_md89',1,'']]],
  ['the_20de_20boor_20algorithm_6',['Evaluation: the de Boor Algorithm',['../theory_bsplines.html#autotoc_md13',1,'']]],
  ['the_20disc_20edge_7',['Boundary Conditions on the Disc Edge',['../theory_special_domains.html#autotoc_md61',1,'']]],
  ['the_20observation_20matrix_8',['The Observation Matrix',['../theory_surface_fitting.html#autotoc_md39',1,'']]],
  ['the_20origin_9',['Continuity at the Origin',['../theory_special_domains.html#autotoc_md57',1,'']]],
  ['the_20origin_10',['Continuity at the origin',['../tutorial_polar.html#autotoc_md145',1,'']]],
  ['the_20origin_20problem_11',['Analogy with the origin problem',['../theory_special_domains.html#autotoc_md67',1,'']]],
  ['the_20polar_20domain_12',['The polar domain',['../theory_special_domains.html#autotoc_md54',1,'']]],
  ['the_20pole_20problem_13',['The Pole Problem',['../theory_special_domains.html#autotoc_md66',1,'The Pole Problem'],['../tutorial_sphere.html#autotoc_md156',1,'The Pole Problem']]],
  ['the_20problem_14',['The problem',['../theory_special_domains.html#autotoc_md58',1,'']]],
  ['the_20smoothing_20factor_15',['the Smoothing Factor',['../theory_curve_fitting.html#autotoc_md25',1,'Choosing the Smoothing Factor'],['../theory_surface_fitting.html#autotoc_md48',1,'Choosing the Smoothing Factor']]],
  ['the_20smoothing_20norm_16',['The Smoothing Norm',['../theory_surface_fitting.html#autotoc_md47',1,'']]],
  ['the_20smoothing_20problem_17',['The Smoothing Problem',['../theory_curve_fitting.html#autotoc_md23',1,'']]],
  ['the_20spherical_20domain_18',['The spherical domain',['../theory_special_domains.html#autotoc_md63',1,'']]],
  ['theory_19',['Theory',['../theory_curve_fitting.html',1,'Curve Fitting Theory'],['../theory_surface_fitting.html',1,'Surface Fitting Theory']]],
  ['torus_20',['Example: Fitting a Torus',['../tutorial_grid_surface.html#autotoc_md139',1,'']]],
  ['transform_21',['Normalized polar transform',['../theory_special_domains.html#autotoc_md55',1,'']]],
  ['tt_22',['tt',['../tutorial_polar.html#autotoc_md148',1,'Gridded Data: &lt;tt&gt;fitpack_grid_polar&lt;/tt&gt;'],['../tutorial_sphere.html#autotoc_md162',1,'Gridded Sphere Data — &lt;tt&gt;fitpack_grid_sphere&lt;/tt&gt;'],['../tutorial_polar.html#autotoc_md146',1,'Scattered Data: &lt;tt&gt;fitpack_polar&lt;/tt&gt;'],['../tutorial_sphere.html#autotoc_md158',1,'Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;']]],
  ['tt_20fitpack_5fgrid_5fpolar_20tt_23',['Gridded Data: &lt;tt&gt;fitpack_grid_polar&lt;/tt&gt;',['../tutorial_polar.html#autotoc_md148',1,'']]],
  ['tt_20fitpack_5fgrid_5fsphere_20tt_24',['Gridded Sphere Data — &lt;tt&gt;fitpack_grid_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md162',1,'']]],
  ['tt_20fitpack_5fpolar_20tt_25',['Scattered Data: &lt;tt&gt;fitpack_polar&lt;/tt&gt;',['../tutorial_polar.html#autotoc_md146',1,'']]],
  ['tt_20fitpack_5fsphere_20tt_26',['Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md158',1,'']]],
  ['tutorial_27',['Tutorial',['../tutorial_grid_surface.html',1,'Grid and Parametric Surface Tutorial'],['../tutorial_polar.html',1,'Polar Domain Fitting Tutorial'],['../tutorial_surface.html',1,'Scattered Surface Fitting Tutorial'],['../tutorial_sphere.html',1,'Spherical Spline Fitting Tutorial']]]
];
