var searchData=
[
  ['s_0',['Choosing S',['../tutorial_curve.html#autotoc_md72',1,'']]],
  ['scattered_20data_20fitting_20surfit_1',['Scattered Data Fitting (surfit)',['../theory_surface_fitting.html#autotoc_md38',1,'']]],
  ['scattered_20data_3a_20tt_20fitpack_5fpolar_20tt_2',['Scattered Data: &lt;tt&gt;fitpack_polar&lt;/tt&gt;',['../tutorial_polar.html#autotoc_md146',1,'']]],
  ['scattered_20fitting_3',['Grid vs Scattered Fitting',['../tutorial_grid_surface.html#autotoc_md140',1,'']]],
  ['scattered_20sphere_20data_20—_20tt_20fitpack_5fsphere_20tt_4',['Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md158',1,'']]],
  ['scattered_20surface_20fitting_20tutorial_5',['Scattered Surface Fitting Tutorial',['../tutorial_surface.html',1,'']]],
  ['sections_6',['Cross-sections',['../tutorial_surface.html#autotoc_md122',1,'']]],
  ['sections_20and_20derivative_20splines_7',['Cross-Sections and Derivative Splines',['../tutorial_grid_surface.html#autotoc_md133',1,'']]],
  ['set_20convexity_20flags_8',['Step 1 — Load Data and Set Convexity Flags',['../tutorial_convex_curve.html#autotoc_md107',1,'']]],
  ['set_5fconstraints_9',['set_constraints',['../structfitpack__parametric__curves_1_1fitpack__constrained__curve.html#a3a1b55ccb2f48c871d27d633453b7f05',1,'fitpack_parametric_curves::fitpack_constrained_curve']]],
  ['set_5fconvexity_10',['set_convexity',['../structfitpack__convex__curves_1_1fitpack__convex__curve.html#a7ed6d5f5b48c41fad2a8bfc16e9e6e6c',1,'fitpack_convex_curves::fitpack_convex_curve']]],
  ['set_5forigin_5fbc_11',['set_origin_bc',['../structfitpack__gridded__polar_1_1fitpack__grid__polar.html#a1860a62261667c477d8afd882f3b9661',1,'fitpack_gridded_polar::fitpack_grid_polar']]],
  ['setting_20constraints_12',['Setting Constraints',['../tutorial_parametric_curves.html#autotoc_md100',1,'']]],
  ['shared_20knot_20vector_13',['Shared Knot Vector',['../theory_curve_fitting.html#autotoc_md29',1,'']]],
  ['shortcut_14',['Constructor Shortcut',['../tutorial_convex_curve.html#autotoc_md112',1,'']]],
  ['smooth_20function_20on_20a_20unit_20disc_15',['Example: smooth function on a unit disc',['../tutorial_polar.html#autotoc_md147',1,'']]],
  ['smoothing_16',['smoothing',['../structfitpack__fitters_1_1fitpack__fitter.html#a2ef622360564515e14a40a24a1896163',1,'fitpack_fitters::fitpack_fitter']]],
  ['smoothing_20and_20interpolation_17',['Smoothing and Interpolation',['../tutorial_periodic_curve.html#autotoc_md90',1,'']]],
  ['smoothing_20factor_18',['Smoothing Factor',['../theory_curve_fitting.html#autotoc_md25',1,'Choosing the Smoothing Factor'],['../theory_surface_fitting.html#autotoc_md48',1,'Choosing the Smoothing Factor']]],
  ['smoothing_20formulation_19',['Smoothing Formulation',['../theory_surface_fitting.html#autotoc_md41',1,'']]],
  ['smoothing_20norm_20',['The Smoothing Norm',['../theory_surface_fitting.html#autotoc_md47',1,'']]],
  ['smoothing_20problem_21',['The Smoothing Problem',['../theory_curve_fitting.html#autotoc_md23',1,'']]],
  ['smoothing_20sweep_22',['Smoothing Sweep',['../tutorial_curve.html#autotoc_md81',1,'Smoothing Sweep'],['../tutorial_surface.html#autotoc_md124',1,'Smoothing Sweep']]],
  ['sphere_20data_20—_20tt_20fitpack_5fgrid_5fsphere_20tt_23',['Gridded Sphere Data — &lt;tt&gt;fitpack_grid_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md162',1,'']]],
  ['sphere_20data_20—_20tt_20fitpack_5fsphere_20tt_24',['Scattered Sphere Data — &lt;tt&gt;fitpack_sphere&lt;/tt&gt;',['../tutorial_sphere.html#autotoc_md158',1,'']]],
  ['spheres_25',['Pole boundary conditions for gridded spheres',['../theory_special_domains.html#autotoc_md69',1,'']]],
  ['spherical_20coordinates_26',['Spherical Coordinates',['../theory_special_domains.html#autotoc_md62',1,'']]],
  ['spherical_20domain_27',['The spherical domain',['../theory_special_domains.html#autotoc_md63',1,'']]],
  ['spherical_20domains_28',['Spherical Domains',['../theory_special_domains.html',1,'Polar and Spherical Domains'],['../book_reference.html#autotoc_md6',1,'Polar and Spherical Domains']]],
  ['spherical_20harmonic_20test_20function_29',['Example: Spherical Harmonic Test Function',['../tutorial_sphere.html#autotoc_md161',1,'']]],
  ['spherical_20harmonics_20connection_30',['Spherical Harmonics Connection',['../tutorial_sphere.html#autotoc_md157',1,'']]],
  ['spherical_20spline_20fitting_20tutorial_31',['Spherical Spline Fitting Tutorial',['../tutorial_sphere.html',1,'']]],
  ['spiral_20with_20prescribed_20tangents_32',['Example: Spiral with Prescribed Tangents',['../tutorial_parametric_curves.html#autotoc_md101',1,'']]],
  ['spline_33',['Derivative spline',['../tutorial_surface.html#autotoc_md123',1,'']]],
  ['spline_20as_20a_20linear_20combination_34',['Spline as a Linear Combination',['../theory_bsplines.html#autotoc_md12',1,'']]],
  ['spline_20basis_20functions_35',['B-Spline Basis Functions',['../theory_bsplines.html#autotoc_md8',1,'']]],
  ['spline_20coefficient_20conditions_36',['B-Spline Coefficient Conditions',['../theory_curve_fitting.html#autotoc_md33',1,'']]],
  ['spline_20fitting_20tutorial_37',['Spherical Spline Fitting Tutorial',['../tutorial_sphere.html',1,'']]],
  ['spline_20foundations_38',['B-Spline Foundations',['../theory_bsplines.html',1,'']]],
  ['splines_39',['Splines',['../tutorial_grid_surface.html#autotoc_md133',1,'Cross-Sections and Derivative Splines'],['../theory_curve_fitting.html#autotoc_md26',1,'Periodic Splines'],['../theory_surface_fitting.html#autotoc_md37',1,'Tensor Product Splines'],['../theory_bsplines.html#autotoc_md17',1,'Tensor Products for Bivariate Splines']]],
  ['squares_20formulation_40',['Least-Squares Formulation',['../theory_surface_fitting.html#autotoc_md40',1,'']]],
  ['squares_20with_20fixed_20knots_41',['Least-Squares with Fixed Knots',['../theory_curve_fitting.html#autotoc_md20',1,'']]],
  ['step_42',['Step-by-step',['../tutorial_curve.html#autotoc_md74',1,'']]],
  ['step_201_20—_20load_20data_20and_20set_20convexity_20flags_43',['Step 1 — Load Data and Set Convexity Flags',['../tutorial_convex_curve.html#autotoc_md107',1,'']]],
  ['step_202_20—_20fit_20with_20constraints_44',['Step 2 — Fit with Constraints',['../tutorial_convex_curve.html#autotoc_md108',1,'']]],
  ['step_203_20—_20evaluate_20and_20inspect_45',['Step 3 — Evaluate and Inspect',['../tutorial_convex_curve.html#autotoc_md109',1,'']]],
  ['step_20by_20step_46',['Step-by-step',['../tutorial_curve.html#autotoc_md74',1,'']]],
  ['structure_47',['Structure',['../theory_surface_fitting.html#autotoc_md45',1,'Kronecker Product Structure'],['../theory_curve_fitting.html#autotoc_md21',1,'Normal Equations and Banded Structure']]],
  ['summary_48',['Summary',['../tutorial_curve.html#autotoc_md82',1,'API Summary'],['../tutorial_convex_curve.html#autotoc_md113',1,'API Summary'],['../theory_curve_fitting.html#autotoc_md36',1,'Summary'],['../theory_surface_fitting.html#autotoc_md52',1,'Summary'],['../tutorial_parametric_curves.html#autotoc_md104',1,'Summary']]],
  ['surface_20evaluation_49',['Surface Evaluation',['../book_reference.html#autotoc_md5',1,'']]],
  ['surface_20fitting_202d_50',['Surface Fitting (2D)',['../book_reference.html#autotoc_md4',1,'']]],
  ['surface_20fitting_20theory_51',['Surface Fitting Theory',['../theory_surface_fitting.html',1,'']]],
  ['surface_20fitting_20tutorial_52',['Scattered Surface Fitting Tutorial',['../tutorial_surface.html',1,'']]],
  ['surface_20tutorial_53',['Grid and Parametric Surface Tutorial',['../tutorial_grid_surface.html',1,'']]],
  ['surfaces_54',['Surfaces',['../tutorial_grid_surface.html#autotoc_md136',1,'Multi-Component Surfaces'],['../theory_surface_fitting.html#autotoc_md50',1,'Parametric Surfaces']]],
  ['surfit_55',['Scattered Data Fitting (surfit)',['../theory_surface_fitting.html#autotoc_md38',1,'']]],
  ['sweep_56',['Sweep',['../tutorial_curve.html#autotoc_md81',1,'Smoothing Sweep'],['../tutorial_surface.html#autotoc_md124',1,'Smoothing Sweep']]],
  ['sx_57',['sx',['../structfitpack__convex__curves_1_1fitpack__convex__curve.html#ae36b2d943b41432d5388d2e3aed70cf6',1,'fitpack_convex_curves::fitpack_convex_curve']]]
];
